name: QuickInput-CI
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build_windows:
    runs-on: windows-latest
    steps:
      - name: 拉取项目源码
        uses: actions/checkout@v4

      - name: MSVC编译环境
        uses: ilammy/msvc-dev-cmd@v1

      - name: Python环境
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: 安装aqtinstall
        run: |
          python -m pip install --upgrade pip
          python -m pip install aqtinstall==3.3.* --default-timeout=120

      - name: 安装Qt6.8.0
        id: qt_install
        uses: jurplel/install-qt-action@v4
        with:
          version: '6.8.0'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2022_64'

      - name: Qt加入环境变量
        env:
          QT_INSTALL_DIR: ${{ steps.qt_install.outputs.QT_INSTALL_DIR }}
        run: |
          echo "$env:QT_INSTALL_DIR\bin" | Out-File -FilePath $env:GITHUB_PATH -Append

      - name: CI下载解压QFrameless源码
        run: |
          Invoke-WebRequest -Uri "https://github.com/wangwenx190/framelesshelper/archive/refs/tags/v2.10.0.zip" -OutFile qframeless.zip
          Expand-Archive qframeless.zip -DestinationPath ./ext
        shell: powershell

      - name: 生成pro构建文件
        run: |
          "DEFINES += WIN32_LEAN_AND_MEAN NOMINMAX`nQT += core gui widgets network`nLIBS += shell32.lib`nSOURCES += source/main.cpp source/src/action.cpp source/src/func.cpp source/src/init.cpp source/src/input.cpp source/src/interpreter.cpp source/src/json.cpp source/src/lang.cpp source/src/macro.cpp source/src/scriptinterpreter.cpp source/src/thread.cpp source/src/trigger.cpp source/src/type.cpp source/ui/MsgViewUi.cpp source/ui/VarViewUi.cpp source/ui/UpdateUi.cpp source/ui/TriggerUi.cpp source/ui/SettingsUi.cpp source/ui/RecordUi.cpp source/ui/PopsUi.cpp source/ui/HelpUi.cpp source/ui/MainUi.cpp source/ui/MacroUi.cpp source/ui/FuncUi.cpp source/ui/EditUi.cpp source/ui/AboutUi.cpp`nHEADERS += source/src/*.h source/ui/*.h`nINCLUDEPATH += source source/src source/ui ./ext/framelesshelper-2.10.0/src`nSOURCES += ./ext/framelesshelper-2.10.0/src/core/framelesshelper.cpp`nHEADERS += ./ext/framelesshelper-2.10.0/src/core/framelesshelper.h" | Set-Content buildtemp.pro -Encoding utf8

      - name: qmake生成Makefile
        run: qmake buildtemp.pro

      - name: nmake编译
        run: nmake

      - name: Qt部署依赖
        run: windeployqt release\*.exe

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: QuickInput-Win-x64
          path: release/**/*
